### ISSUE TITLE
Required npm versions mismatch

### ISSUE THREAD

**Issue by nachaos** [epicweb-dev/react-fundamentals#336]
The fix introduced [here](https://github.com/kentcdodds/react-fundamentals/commit/c0a23cf39faeb638c75c00d14d3bf8919082392b) was not reflected on the epicreact.dev website.

https://epicreact.dev/modules/react-fundamentals/react-fundamentals-welcome
> [npm](https://www.npmjs.com/) v6 or greater
![image](https://user-images.githubusercontent.com/30051331/229794296-928470a7-7d1f-472a-a6d8-178cc7f78d0a.png)

When trying to run the `setup` script with npm v6, it fails

```
➜  react-fundamentals git:(main) npm run setup --silent
▶️  Starting workshop setup...
🚨  npm version is 8.11.0 which is out of date. Please install npm@8.16.0 or greater

Error: npm version is out of date
```

**Comment by kentcdodds** [comment]
I'll have the team get that fixed. Thanks!
