### ISSUE TITLE
Confusing sentence in the markdown for "Creating custom components" in React Fundamentals

### ISSUE THREAD

**Issue by jkrooncoding** [epicweb-dev/react-fundamentals#339]
I am currently doing the React Fundamentals course and stumbled upon the first sentence under the "Background" heading in the "Creating custom components" section. To me, this sentence was very confusing. My suggestion would be to remove the words "which you do"; It would still cover the correct meaning of the sentence I believe.

**Comment by kentcdodds** [comment]
Hi @jkrooncoding, would you be interested in opening a pull request? It would help in comparing before/after and make it easier for me to accept the change.
