### ISSUE TITLE
Missing automatic browser reloading [KCD_WS] 

### ISSUE THREAD

**Issue by moelzanaty3** [epicweb-dev/react-fundamentals#360]
Hey @kentcdodds , 

First off, big thanks for your hard work on this! 🙌 

I've noticed a little hiccup though. It seems there's a script, `kcd_ws.js`, added to every exercise, but it's missing from the public folder. Not sure if this was intentional or an oversight. It would be great if we could address this by either adding it or, if unnecessary, I'm happy to raise a PR to remove its import from each exercise.

Thanks again for the awesome workshop! 😊

Best regards,
Mo

**Comment by moelzanaty3** [comment]
surprisingly it's worked, not sure what was the problem but it might be problem at my browser,

**Comment by kentcdodds** [comment]
Yeah, that request hits this route within the workshop app: https://github.com/epicweb-dev/kcdshop/blob/main/packages/workshop-app/app/routes/_app%2B/app.%24appName%2B/kcd_ws%5B.js%5D.ts

So it's not a file on the file system. Instead it's generated at request time :) Cheers!
