### ISSUE TITLE
Union -> Intersection

### ISSUE THREAD

**Issue by Creeland** [epicweb-dev/react-fundamentals#372]
https://github.com/epicweb-dev/react-fundamentals/blob/44fe088588cc5287386e6ae015359cadba3bcc28/exercises/06.styling/03.problem.size-prop/index.tsx#L3-L11

In the problem there's a hint that says to union this with an object but it looks like you're using an intersection in the solution.

https://github.com/epicweb-dev/react-fundamentals/blob/44fe088588cc5287386e6ae015359cadba3bcc28/exercises/06.styling/03.solution.size-prop/index.tsx#L6-L8

Would it make sense to add a docs link in the problem README and change the hint here?

**Comment by kentcdodds** [comment]
Yes, we should probably do that! My mistake calling this intersection a union 😅
