### ISSUE TITLE
npm run setup fails

### ISSUE THREAD

**Issue by Jatz** [epicweb-dev/react-fundamentals#381]
I'm unable to get the workshop running. It used to work for me, but it no longer does.

When running the following:
git clone --depth 1 https://github.com/epicweb-dev/react-fundamentals.git
cd react-fundamentals
npm run setup

When running npm run setup, the workshop setup starts and then fails with the following error:
npm ERR! Invalid comparator: npm:types-react@19.0.0-alpha.5

Here are my versions
Git: version 2.34.1.windows.1
Node: v20.17.0
npm: 9.2.0

And here is my debug log file:
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\reactdev\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@9.2.0
2 info using node@v20.17.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\reactdev\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:E:\Dev\Home\EpicReact\react-fundamentals\.npmrc Completed in 1ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:C:\Users\reactdev\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\reactdev\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 12ms
17 timing npm:load:configload Completed in 12ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm exec https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733 -q
21 verbose argv "exec" "--yes" "--" "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" "-q"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 2ms
24 timing npm:load:display Completed in 3ms
25 verbose logfile logs-max:10 dir:C:\Users\reactdev\AppData\Local\npm-cache\_logs\2024-09-28T12_06_44_009Z-
26 verbose logfile C:\Users\reactdev\AppData\Local\npm-cache\_logs\2024-09-28T12_06_44_009Z-debug-0.log
27 timing npm:load:logFile Completed in 4ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 21ms
31 silly logfile start cleaning logs, removing 2 files
32 timing config:load:flatten Completed in 0ms
33 silly logfile done cleaning log files
34 timing arborist:ctor Completed in 1ms
35 timing command:exec Completed in 12ms
36 verbose stack TypeError: Invalid comparator: npm:types-react@19.0.0-alpha.5
36 verbose stack     at Comparator.parse (C:\Users\reactdev\AppData\Roaming\npm\node_modules\npm\node_modules\semver\classes\comparator.js:38:13)
36 verbose stack     at new Comparator (C:\Users\reactdev\AppData\Roaming\npm\node_modules\npm\node_modules\semver\classes\comparator.js:22:10)
36 verbose stack     at C:\Users\reactdev\AppData\Roaming\npm\node_modules\npm\node_modules\semver\classes\range.js:133:47
36 verbose stack     at Array.map (<anonymous>)
36 verbose stack     at Range.parseRange (C:\Users\reactdev\AppData\Roaming\npm\node_modules\npm\node_modules\semver\classes\range.js:133:35)
36 verbose stack     at C:\Users\reactdev\AppData\Roaming\npm\node_modules\npm\node_modules\semver\classes\range.js:34:22
36 verbose stack     at Array.map (<anonymous>)
36 verbose stack     at new Range (C:\Users\reactdev\AppData\Roaming\npm\node_modules\npm\node_modules\semver\classes\range.js:34:8)
36 verbose stack     at Object.intersects (C:\Users\reactdev\AppData\Roaming\npm\node_modules\npm\node_modules\semver\ranges\intersects.js:3:8)
36 verbose stack     at OverrideSet.getEdgeRule (C:\Users\reactdev\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\override-set.js:53:18)
37 verbose cwd E:\Dev\Home\EpicReact\react-fundamentals
38 verbose Windows_NT 10.0.22631
39 verbose node v20.17.0
40 verbose npm  v9.2.0
41 error Invalid comparator: npm:types-react@19.0.0-alpha.5
42 verbose exit 1
43 timing npm Completed in 53ms
44 verbose code 1
45 error A complete log of this run can be found in:
45 error     C:\Users\reactdev\AppData\Local\npm-cache\_logs\2024-09-28T12_06_44_009Z-debug-0.log

**Comment by Jatz** [comment]
I managed to resolve the issue by upgrading to the latest version of npm:
`npm install -g npm`

When running `npm --version`, it previously was 9.2.0. After upgrading to the latest version of npm, my version is now 10.8.3. And I can finally launch the workshop again

**Comment by kentcdodds** [comment]
I'm glad you got it working!
