### ISSUE TITLE
Mocklogs[0] is undefined - test failing with this error starting on exercise 07/04 & most of the 07 lessons

### ISSUE THREAD

**Issue by MikeRatcliffe** [epicweb-dev/react-fundamentals#397]
This was originally logged by @Creeland  as issue #374, but you couldn't reproduce it, so you closed it.

In `exercises/07.forms/04.solution.submit/submit.test.ts` (and most of the 07 lessons) you programmaticly click `[submit]` on the form, but in Firefox most events are blocked inside hidden iframes (`submit()`, `click()` etc.)

There's an 8-year-old bug [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1306686), which is a resurrected version of a [23-year-old bug](https://bugzilla.mozilla.org/show_bug.cgi?id=100533) that explains that when iframes are hidden the presentation context is torn down, so there is then no way to know for sure where to target events.

To fix this you'd have to show the iframe, click submit and then hide it again. Failing that, users can expand the test so that the form is visible and rerun just that test and it will pass.

Hey, I never worked on that part of the browser, so don't blame me ;)

**Comment by kentcdodds** [comment]
Holy smokes 🤯

Well, thank you for sharing all that context 😆

I'll have to come up with another way to test this (and many other things) when the iframe is hidden 🤔

**Comment by MikeRatcliffe** [comment]
Maybe just set the height of the `<div>`, which contains the `<iframe>` to `height: 0; overflow: hidden` instead of hiding it?
