### ISSUE TITLE
Failing tests show as passing (Error Boundaries; 09.01 & 09.02)

### ISSUE THREAD

**Issue by ianjmacintosh** [epicweb-dev/react-fundamentals#399]
I ran the tests for the "Error Boundaries: Other Errors" lesson (`/exercises/09.errors/02.solution.show-boundary/error-boundary.test.ts`) and saw the tests show as passing even before I started the exercise, but the console shows that the assertions are not being satisfied.

I went back to the previous chapter (09.01) and see the same thing happening in `/exercises/09.errors/01.solution.composition/error-boundary.test.ts` so I started troubleshooting there.

```
test.ts:35 Uncaught (in promise) Error: Error boundary is rendered immediately due to render error
```

It seems like something in `testStep` isn't behaving right. I did a _little_ bit of digging in https://github.com/epicweb-dev/epicshop/blob/main/packages/workshop-utils/src/test.ts but I got lost real fast.

<img width="1556" alt="Workshop app shows tests passing, console shows tests failing" src="https://github.com/user-attachments/assets/f1cfc54e-2a03-47a9-8eaa-105b2ab3e563">

**Comment by kentcdodds** [comment]
Thanks for bringing this up! I forgot to await the test step.

**Comment by ianjmacintosh** [comment]
> Thanks for bringing this up! I forgot to await the test step.

Thank you! And now that you've shown me the fix, I'm going to apply the same for `/exercises/09.errors/02.solution.show-boundary/error-boundary.test.ts` brb

**Comment by ianjmacintosh** [comment]
nm, you beat me to it in 14803825683d3e2bd7484fa8fdff31896001ce3f

Thanks again 🙌
