### ISSUE TITLE
permission denied, open '/Users/<user>/.epicshop/data.json'

### ISSUE THREAD

**Issue by maliheNoroozi** [epicweb-dev/react-fundamentals#402]
I cloned react-fundamentals and tried to ran the setup command. While runing setup command it gave permission error, then I ran it with sudo, and it finished setting up.
Now that I am running npm run start, and open the browser, I am getting this error

Browser:
<img width="1055" alt="Screenshot 2024-10-19 at 16 50 48" src="https://github.com/user-attachments/assets/a52608a6-047d-4e61-9090-86168667d4cd">

Terminal
<img width="960" alt="Screenshot 2024-10-19 at 16 49 45" src="https://github.com/user-attachments/assets/7f046012-ee3b-4f33-ba4c-0862ebbc6fd1">

My system is MacOs
npm version: 10.9.0
node vesrion: v23.0.0
git version: 2.33.0

**Comment by kentcdodds** [comment]
Huh, this is a new one. You should probably have access to your home directory. ChatGPT says you can run this to get access:

```
sudo chmod -R 755 /Users/malihenorouzi/.epicshop
```

Note: this requires `sudo` so it will ask for your password.

I hope that helps!

**Comment by maliheNoroozi** [comment]
Thanks for the answer. I still have the same problem.

As you can see there is no data.json file in .epicshop directory. I was wondering if there is a way I can uninstall all setup and do it again. Maybe it helps, don't know. 

<img width="864" alt="Screenshot 2024-10-20 at 14 53 35" src="https://github.com/user-attachments/assets/7c9e4557-bb0f-4000-90c3-7a4d49f8032b">

**Comment by kentcdodds** [comment]
Glad you got it working! Sorry for the trouble.
