### ISSUE TITLE
Editor not opening

### ISSUE THREAD

**Issue by BickelLukas** [epicweb-dev/react-fundamentals#403]
![image](https://github.com/user-attachments/assets/e741f7fa-4463-4397-94ef-8811edf3ebbf)

I'm guessing the problem is spaces in the path. VsCode is installed at `C:\Users\lukas.bickel\AppData\Local\Programs\Microsoft VS Code\Code.exe`

**Comment by kentcdodds** [comment]
Did you try to customize the path in a `.env` file like this? https://www.epicreact.dev/get-started#troubleshooting-workshop-file-links

If so, make sure you keep the quotes around.

**Comment by BickelLukas** [comment]
With the env file it works so ill close this issue. But shouldn't it work with spaces in the path by default in windows?

**Comment by kentcdodds** [comment]
It seems to for most people. Hard to debug everyone's machines so the workaround is the best I can do when it doesn't work for the few.
